// All player-visible text. Switching language = swapping this module's data.
export const STR = {
  title: "Chess 3D",
  menu: {
    vsComputer: "Play vs Computer",
    passPlay: "Pass & Play",
    online: "Play Online",
    subtitle: "Full chess. Real 3D. Any device.",
    side: "Your side",
    white: "White",
    black: "Black",
    random: "Random",
    difficulty: "Computer strength",
    levels: ["Beginner", "Casual", "Club", "Expert"],
    time: "Time control",
    times: {
      "1+0": "Bullet 1|0", "3+2": "Blitz 3|2", "5+0": "Blitz 5|0",
      "10+0": "Rapid 10|0", "15+10": "Rapid 15|10", "inf": "Unlimited",
    },
    start: "Start game",
    back: "Back",
    onlineHint: "You'll get an invite link to send to a friend.",
  },
  hud: {
    you: "You", computer: "Computer", white: "White", black: "Black",
    opponent: "Opponent", spectating: "Spectating",
    yourTurn: "Your move", theirTurn: "Waiting for opponent…",
    whiteTurn: "White to move", blackTurn: "Black to move",
    thinking: "Computer is thinking…",
    check: "Check!",
    newGame: "New game", flip: "Flip board", resign: "Resign",
    draw: "Offer draw", undo: "Takeback", sound: "Sound",
    moves: "Moves",
    drawOffered: "Draw offered — accept?", accept: "Accept", decline: "Decline",
    drawOfferSent: "Draw offer sent",
    confirmResign: "Resign this game?", yes: "Yes", no: "No",
  },
  online: {
    waiting: "Waiting for an opponent…",
    invite: "Send this link to a friend:",
    copy: "Copy link", copied: "Copied!",
    connecting: "Connecting…",
    disconnected: "Disconnected — reconnecting…",
    youAreWhite: "You play White", youAreBlack: "You play Black",
    chooseTime: "Choose the time control", waitConfig: "White is choosing the time control…",
    playAgain: "Play again",
  },
  over: {
    checkmate: "Checkmate",
    stalemate: "Stalemate",
    resignation: "by resignation",
    timeout: "on time",
    agreement: "by agreement",
    threefold: "by threefold repetition",
    fifty: "by the 50-move rule",
    material: "insufficient material",
    whiteWins: "White wins", blackWins: "Black wins",
    youWin: "You win! 🎉", youLose: "You lose", draw: "Draw",
    rematch: "Rematch", menu: "Main menu",
  },
  promo: { title: "Promote to", q: "Queen", r: "Rook", b: "Bishop", n: "Knight" },
  err: { generic: "Something went wrong" },
};
